[package]
name = "agent-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "^4.5.53", features = ["derive"] }
tokio = { version = "^1.48.0", features = ["full"] }
agent = { path = "../agent" }
rustyline = "^17.0.2"
aws-sdk-bedrockruntime = "^1.118.0"
